image: WMF 5
install:
- ps: .\buildscripts\install.ps1
build_script:
- ps: .\buildscripts\build.ps1
test_script:
- ps: .\buildscripts\test.ps1
after_test:
- ps: .\buildscripts\publish.ps1

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 0SXYOxoVQQeHXAdongVM4NBe7RMvYqowUywID9d1zpyIAM5Qa7cL9GeSFLc0mfGeSVVdL0c44XhEtei7PEHnsHdN057VRixyBqBRLBc5QAo=